Добавил проверки на наличие нужных файлов

diff --git a/ezldap b/ezldap
--- a/ezldap
+++ b/ezldap
@@ -1,7 +1,14 @@
 #!/bin/bash
 
 #########################CONFIG############################
-source /etc/ezldap/ezldap.conf
+CONFIG_FILE=/etc/ezldap/ezldap.conf
+if test -f "$CONFIG_FILE"; then
+    source /etc/ezldap/ezldap.conf
+else
+    echo "Config file not found :("
+    echo "Try to create a new one using /etc/ezldap/install.sh script"
+    exit 1
+fi
 ###########################END#############################
 
 
